export enum MutationTypes {
	SET_CONFIGURATION = 'setConfiguration',
	SET_MESSAGES = 'setMessages',
	SET_WORLDS = 'setWorlds',
	SET_COMPONENTS = 'setComponents',
	SET_MARKER_SETS = 'setMarkerSets',
	ADD_WORLD = 'addWorld',
	SET_WORLD_STATE = 'setWorldState',
	SET_UPDATE_TIMESTAMP = 'setUpdateTimestamp',
	INCREMENT_REQUEST_ID = 'incrementRequestId',
	SET_PLAYERS = 'setPlayers',
	SET_PLAYERS_ASYNC = 'setPlayersAsync',
	SYNC_PLAYERS = 'syncPlayers',
	SET_CURRENT_MAP = 'setCurrentMap',
	SET_CURRENT_PROJECTION = 'setCurrentProjection',
	FOLLOW_PLAYER = 'followPlayer',
	CLEAR_FOLLOW = 'clearFollow',
}